import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../branding/avera_brand_assets.dart';
import '../subscription/subscription_payment_gateway.dart';

class SubscriptionReceiptService {
  const SubscriptionReceiptService();

  Future<void> printReceipt({
    required String clinicName,
    required SubscriptionPaymentRecord payment,
  }) async {
    final bytes = await buildReceipt(clinicName: clinicName, payment: payment);
    await Printing.layoutPdf(
      name: 'AVERA-${payment.reference}.pdf',
      onLayout: (_) async => bytes,
    );
  }

  Future<Uint8List> buildReceipt({
    required String clinicName,
    required SubscriptionPaymentRecord payment,
  }) async {
    final document = pw.Document();
    final logoBytes = await rootBundle.load(AveraBrandAssets.primaryLogo);
    final logo = pw.MemoryImage(logoBytes.buffer.asUint8List());
    final paidDate = payment.paidAt ?? payment.createdAt;
    final amount = NumberFormat.simpleCurrency(
      name: payment.currency,
      decimalDigits: 0,
    ).format(payment.amountMinor / 100);
    document.addPage(
      pw.Page(
        build: (_) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              children: [
                pw.Image(logo, width: 42, height: 42),
                pw.SizedBox(width: 12),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'AVERA',
                      style: pw.TextStyle(
                        fontSize: 22,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.Text(clinicName),
                  ],
                ),
              ],
            ),
            pw.SizedBox(height: 32),
            pw.Text(
              'Subscription Payment Receipt',
              style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 20),
            _line('Receipt number', 'AVR-${payment.reference}'),
            _line('Clinic', clinicName),
            _line('Plan', payment.plan.label),
            _line('Billing cycle', payment.billingCycle.name),
            _line('Payment date', DateFormat.yMMMd().add_jm().format(paidDate)),
            _line('Amount', amount),
            _line('Payment reference', payment.reference),
            _line('Status', payment.status),
            _line('Gateway', 'Paystack'),
            pw.Spacer(),
            pw.Divider(),
            pw.Text(
              'Generated by AVERA veterinary practice management.',
              style: const pw.TextStyle(fontSize: 9),
            ),
          ],
        ),
      ),
    );
    return document.save();
  }

  pw.Widget _line(String label, String value) => pw.Padding(
    padding: const pw.EdgeInsets.only(bottom: 12),
    child: pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.SizedBox(
          width: 130,
          child: pw.Text(
            label,
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),
        ),
        pw.Expanded(child: pw.Text(value)),
      ],
    ),
  );
}
